############# English navigation ##############
# main menu    
  
[[main]]
name = "Service"
URL = "service"
weight = 1

[[main]]
name = "Pricing"
URL = "pricing"
weight = 2

[[main]]
name = "Contact"
URL = "contact"
weight = 3

[[main]]
name = "FAQ"
URL = "faq"
weight = 4
  
[[main]]
name = "About"
URL = "about"
weight = 5
  
  

[[footer]]
name = "About us"
URL = "about"

[[footer]]
name = "Contact us"
URL = "contact"

[[footer]]
name = "Privacy Policy"
URL = "#"